logging:
  level:
    io.zenwave360.example: DEBUG
    org.hibernate.SQL: DEBUG
#    org.springframework.cloud.stream: DEBUG
#    org.apache.kafka: DEBUG
spring:
  security:
    user:
      name: user
      password: password
      roles: USER
  jpa.hibernate.ddl-auto: update
#  jpa.defer-datasource-initialization: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/zenwave-example?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
